### ISSUE TITLE
Error when doing "gulp serve"

### ISSUE THREAD

**Issue by Woile** [bespokejs/generator-bespoke#33]
After generating my presentation, when doing `gulp serve` I was getting this error. 
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at ConnectApp.server (/home/santiago/proyectos/js/marionette-presentation/node_modules/gulp-connect/index.js:57:19)
    at new ConnectApp (/home/santiago/proyectos/js/marionette-presentation/node_modules/gulp-connect/index.js:37:10)
    at Object.module.exports.server (/home/santiago/proyectos/js/marionette-presentation/node_modules/gulp-connect/index.js:170:12)
    at Gulp.<anonymous> (/home/santiago/proyectos/js/marionette-presentation/gulpfile.js:83:11)
    at module.exports (/home/santiago/proyectos/js/marionette-presentation/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
```

I manage to fix it by changing the configuration of the gulp file in my presentation.
```
gulp.task('connect', ['build'], function() {
  connect.server({
    root: 'dist',
    port: 8081,
    livereload: true
  });
});
```

The file in `app/templates/gulpfile.js` should be checked.

Thank you!

**Comment by hsablonniere** [comment]
This issue will depend on the already running ports of the user. We cannot do anything about it. Let us know if a new issue if we should change the default port from `8080` to something else.
